### PR TITLE
OneStop API documentation Setup + User Docs

### LINKED ISSUE #133: start API Documentation with onestop user api
Start API Documentation for OneStop. We will be using OpenAPI with json syntax and Swagger for automation. 
Create the file structure for the docs, add the basic info file, servers file, and under the 'users' tag, add the paths and schemas for oneStopUser endpoints.
Here is an example: https://swc.iitg.ac.in/irbs/#introduction
Refer to https://swagger.io/specification/ for details on OpenAPI structure and format.

### PR DESCRIPTION
**Pull request by Srayash**
fixes #133 

This pull request introduces the initial setup for the OneStop API documentation using the OpenAPI 3.0 specification in JSON format, with Swagger for automation. The following changes have been made:
- File Structure: Created a new **oneStop-api-docs** folder to store OpenAPI related documentation.
- Basic Info: Added **info.json.**
- Servers: Defined the **servers.json** file with server URLs.
- Users Endpoints: Under the users tag, created paths and schema for OneStop user-related operations.

[x] remove .DS_Store.

### CODE REVIEW

**Comment by Srayash** [comment]
@heet434 kindly, review and give feedback, or merge.

**Comment by heet434** [comment]
@Srayash you'll need to add a router for the docs using swagger-ui-express and add the route on the main server which should be accessible without authorization and security-key headers. I added a route to test the docs structure but there is still some issue and the docs are not rendered even after adding the router. I am attaching an image for reference.
Screenshot 2024-10-18 at 2 45 56 PM
Do add the router for docs and test on your local machine and then push on the same PR. Here's an example on how the router should look: 
Screenshot 2024-10-18 at 2 49 56 PM

**Comment by heet434** [comment]
Hi @Srayash the code is now ready to merge, I made some changes to the basic structure to accommodate the docs in the environment.

**Comment by Srayash** [comment]
Thanks @heet434! It would be highly appreciated if you could add the "hacktoberfest-accepted" label to this PR. 😊

**Pull request merged**
